# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20190119_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_level',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_id',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
