# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190123_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
