# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190123_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice1',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice2',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice3',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice4',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='correctchoice',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
