# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190123_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Level'),
        ),
    ]
