# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190123_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='correctchoice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_id',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
