# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.PositiveIntegerField()),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='choices',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.questions'),
        ),
    ]
